### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by Daniel15** [sdwru/glibc-debian-10#1]
Do you have a patch showing what your changes actually were? At the moment it's hard to tell what changes you've made to glibc in order to make this work.

**Comment by sdwru** [comment]
The patch is in this branch.
https://github.com/sdwru/glibc-debian-10/tree/ported_2.6.32_kernel_compatibility

**Comment by sdwru** [comment]
Or, if you just want to look at the patch file.
https://github.com/sdwru/glibc-debian-10/blob/ported_2.6.32_kernel_compatibility/glibc-2.28/debian/patches/port-v2.6.32-kernel-compat.diff

**Comment by Daniel15** [comment]
Thanks!
